package org.pistonmc.api.plugin.entity;

import manifold.ext.props.rt.api.override;
import manifold.ext.props.rt.api.val;
import org.pistonmc.api.plugin.NamespacedResource;

public enum EntityType implements IEntityType {
    AREA_EFFECT_CLOUD("area_effect_cloud"),
    ARMOR_STAND("armor_stand"),
    ARROW("arrow"),
    BAT("bat"),
    BEE("bee"),
    BLAZE("blaze"),
    BOAT("boat"),
    CAT("cat"),
    CAVE_SPIDER("cave_spider"),
    CHICKEN("chicken"),
    COD("cod"),
    COW("cow"),
    CREEPER("creeper"),
    DOLPHIN("dolphin"),
    DONKEY("donkey"),
    DRAGON_FIREBALL("dragon_fireball"),
    DROWNED("drowned"),
    ELDER_GUARDIAN("elder_guardian"),
    END_CRYSTAL("end_crystal"),
    ENDER_DRAGON("ender_dragon"),
    ENDERMAN("enderman"),
    ENDERMITE("endermite"),
    EVOKER("evoker"),
    EVOKER_FANGS("evoker_fangs"),
    EXPERIENCE_ORB("experience_orb"),
    EYE_OF_ENDER("eye_of_ender"),
    FALLING_BLOCK("falling_block"),
    FIREWORK_ROCKET("firework_rocket"),
    FOX("fox"),
    GHAST("ghast"),
    GIANT("giant"),
    GUARDIAN("guardian"),
    HOGLIN("hoglin"),
    HORSE("horse"),
    HUSK("husk"),
    ILLUSIONER("illusioner"),
    IRON_GOLEM("iron_golem"),
    ITEM("item"),
    ITEM_FRAME("item_frame"),
    FIREBALL("fireball"),
    LEASH_KNOT("leash_knot"),
    LIGHTNING_BOLT("lightning_bolt"),
    LLAMA("llama"),
    LLAMA_SPIT("llama_spit"),
    MAGMA_CUBE("magma_cube"),
    MINECART("minecart"),
    CHEST_MINECART("chest_minecart"),
    COMMAND_BLOCK_MINECART("command_block_minecart"),
    FURNACE_MINECART("furnace_minecart"),
    HOPPER_MINECART("hopper_minecart"),
    SPAWNER_MINECART("spawner_minecart"),
    TNT_MINECART("tnt_minecart"),
    MULE("mule"),
    MOOSHROOM("mooshroom"),
    OCELOT("ocelot"),
    PAINTING("painting"),
    PANDA("panda"),
    PARROT("parrot"),
    PHANTOM("phantom"),
    PIG("pig"),
    PIGLIN("piglin"),
    PIGLIN_BRUTE("piglin_brute"),
    PILLAGER("pillager"),
    POLAR_BEAR("polar_bear"),
    TNT("tnt"),
    PUFFERFISH("pufferfish"),
    RABBIT("rabbit"),
    RAVAGER("ravager"),
    SALMON("salmon"),
    SHEEP("sheep"),
    SHULKER("shulker"),
    SHULKER_BULLET("shulker_bullet"),
    SILVERFISH("silverfish"),
    SKELETON("skeleton"),
    SKELETON_HORSE("skeleton_horse"),
    SLIME("slime"),
    SMALL_FIREBALL("small_fireball"),
    SNOW_GOLEM("snow_golem"),
    SNOWBALL("snowball"),
    SPECTRAL_ARROW("spectral_arrow"),
    SPIDER("spider"),
    SQUID("squid"),
    STRAY("stray"),
    STRIDER("strider"),
    EGG("egg"),
    ENDER_PEARL("ender_pearl"),
    EXPERIENCE_BOTTLE("experience_bottle"),
    POTION("potion"),
    TRIDENT("trident"),
    TRADER_LLAMA("trader_llama"),
    TROPICAL_FISH("tropical_fish"),
    TURTLE("turtle"),
    VEX("vex"),
    VILLAGER("villager"),
    VINDICATOR("vindicator"),
    WANDERING_TRADER("wandering_trader"),
    WITCH("witch"),
    WITHER("wither"),
    WITHER_SKELETON("wither_skeleton"),
    WITHER_SKULL("wither_skull"),
    WOLF("wolf"),
    ZOGLIN("zoglin"),
    ZOMBIE("zombie"),
    ZOMBIE_HORSE("zombie_horse"),
    ZOMBIE_VILLAGER("zombie_villager"),
    ZOMBIFIED_PIGLIN("zombified_piglin"),
    PLAYER("player"),
    FISHING_BOBBER("fishing_bobber");

    @override @val NamespacedResource id;

    EntityType(String name) {
        this.id = NamespacedResource.minecraft(name);
    }
}